services:
  app:
    build: .
    container_name: simple-streamlit-server
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - 80:8501
    volumes:
      - .:/app